# Automatically generated by: ros2nix --flake
{ pkgs, perSystem, ... }:
pkgs.rosPackages.jazzy.buildRosPackage rec {
    pname = "ik-solver";
    version = "0.0.0";

    src = ../../src/ik_solver;

    buildType = "ament_python";
    checkInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-copyright
            ament-flake8
            ament-pep257
            python3Packages.pytest
        ];
    propagatedBuildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            python3Packages.numpy
            rclpy
            perSystem.self.stewart-helpers
            perSystem.self.stewart-interfaces
        ];

    meta = {
        description = "ENAE484 X-HAB Robotic Tunnel: pressure-regulator";
        license = with pkgs.lib.licenses; [ asl20 ];
    };
}
