# Automatically generated by: ros2nix --flake
{ pkgs, ... }:
pkgs.rosPackages.jazzy.buildRosPackage rec {
    pname = "stewart-helpers";
    version = "0.0.0";

    src = ../../src/stewart_helpers;

    buildType = "ament_python";
    checkInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-copyright
            ament-flake8
            ament-pep257
            python3Packages.pytest
        ];
    propagatedBuildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            python3Packages.matplotlib
            python3Packages.numpy
        ];

    meta = {
        description = "ENAE484 X-HAB Robotic Tunnel: stewart-helpers";
        license = with pkgs.lib.licenses; [ asl20 ];
    };
}
