# Automatically generated by: ros2nix --flake
{ pkgs, ... }:
pkgs.rosPackages.jazzy.buildRosPackage rec {
    pname = "stewart-interfaces";
    version = "0.0.0";

    src = ../../src/ros_packages/stewart_interfaces;

    buildType = "ament_cmake";
    buildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-cmake
            rosidl-default-generators
        ];
    checkInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-lint-auto
            ament-lint-common
        ];
    propagatedBuildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            geometry-msgs
            rosidl-default-runtime
        ];
    nativeBuildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-cmake
            rosidl-default-generators
        ];

    meta = {
        description = "ENAE484 X-HAB Robotic Tunnel: stewart-interfaces";
        license = with pkgs.lib.licenses; [ asl20 ];
    };
}
