# Automatically generated by: ros2nix --flake
{ pkgs, ... }:
pkgs.rosPackages.jazzy.buildRosPackage rec {
    pname = "vision-system";
    version = "0.0.0";

    src = ../../src/vision_system;

    buildType = "ament_python";
    checkInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            ament-copyright
            ament-flake8
            ament-pep257
            python3Packages.pytest
        ];
    propagatedBuildInputs =
        with pkgs;
        with pkgs.rosPackages.jazzy;
        [
            python3-tf-transformations
            python3Packages.numpy
            rclpy
            stewart-interfaces
        ];

    meta = {
        description = "ENAE484 X-HAB Robotic Tunnel: vision-system";
        license = with pkgs.lib.licenses; [ "TODO-License-declaration" ];
    };
}
